### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ritvikgautam**
Improved links for better readability.

### CODE REVIEW

**Comment by s4n7h0** [comment]
thanks.

**Comment by ritvikgautam** [comment]
Is there a reason why this wasn't merged?

**Comment by s4n7h0** [comment]
Hey @ritvikgautam, appreciate your feedback. I'm collecting feedbacks/responses from multiple sources and working on a updated release mid next month, along with some more features in the project. Do let me know if any more issues you identified, I will surely look into it.

**Comment by ritvikgautam** [comment]
Sure, thanks!

**Pull request closed without merging**
